services:
  backend:
    build: ./backend
    volumes:
      - ./backend/src:/app/src
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 4005:4005
  db:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 1s
      timeout: 2s
    environment:
      POSTGRES_PASSWORD: example
  redis:
    image: redis
  redis-commander:
    image: rediscommander/redis-commander
    environment:
      - REDIS_HOSTS=redis
    ports:
      - "8081:8081"
